### ISSUE TITLE
srec/srec.c:161: warning: 'comp_err' may be used uninitialized in this function

### ISSUE THREAD

**Issue by javierdlr** [salass00/srec#1]
Hi, when trying to compile I get:
...
cc1: warnings being treated as errors
srec/srec.c: In function 'srec_entry':
srec/srec.c:161: warning: 'comp_err' may be used uninitialized in this function
make: **\* [srec/srec.o] Error 1

setting ''comp_err = 0;' solves such "issue".

**Comment by salass00** [comment]
On 26.09.2016 15:28, javierdlr wrote:

> Hi, when trying to compile I get:
> ...
> cc1: warnings being treated as errors
> srec/srec.c: In function 'srec_entry':
> srec/srec.c:161: warning: 'comp_err' may be used uninitialized in this 
> function
> make: **\* [srec/srec.o] Error 1
> 
> setting ''comp_err = 0;' solves such "issue".

I guess you are using gcc 4.2.4 to compile?

That's just the compiler being overly cautious. The comp_err variable 
can't be used uninitialized because of how the code is written.

I'm using gcc 4.9.2 for compiling and it has a much better code analyser 
so it doesn't give as many useless spam warnings like this one.

Regards,
Fredrik Wikstrom

**Comment by javierdlr** [comment]
yes using GCC 4.2.4.
Ok mark as 'not valid'/resolved. THX

**Comment by javierdlr** [comment]
BTW another error/warning I get is that it can't create SRec (stripped) from .debug, 'cos there exists a drawer named srec. Under linux no problem I guess (srec <> SRec), but on Amiga :-/

**Comment by salass00** [comment]
I renamed the directory to src so it shouldn't cause any more problems.
